'use client'

import { useState, useCallback } from 'react'
import { DiscoveryChat } from '@/components/discovery'
import {
  discoverySavedSessions,
  discoveryCurrentSession,
  discoveryAvailableSources,
} from '@/data/discovery-sample-data'
import type { SavedSession, CurrentSession, QuerySources, ChatMessage } from '@/types'

export default function DiscoveryPage() {
  const [savedSessions, setSavedSessions] = useState<SavedSession[]>(discoverySavedSessions)
  const [currentSession, setCurrentSession] = useState<CurrentSession>(discoveryCurrentSession)

  const handleSendMessage = useCallback((content: string) => {
    const userMessage: ChatMessage = {
      id: `msg-${Date.now()}`,
      role: 'user',
      content,
      timestamp: new Date().toISOString(),
    }

    // Append user message, then simulate an assistant response
    setCurrentSession((prev) => {
      const withUser = { ...prev, messages: [...prev.messages, userMessage] }

      const assistantMessage: ChatMessage = {
        id: `msg-${Date.now() + 1}`,
        role: 'assistant',
        content: `I found some relevant information about "${content}" in your timeline data. This is a mock response — in production, this would be generated by an AI service querying your selected sources.`,
        timestamp: new Date(Date.now() + 500).toISOString(),
      }

      return { ...withUser, messages: [...withUser.messages, assistantMessage] }
    })
  }, [])

  const handleRegenerate = useCallback((messageId: string) => {
    console.log('Regenerate message:', messageId)
  }, [])

  const handleCopyResponse = useCallback((messageId: string) => {
    const message = currentSession.messages.find((m) => m.id === messageId)
    if (message) {
      navigator.clipboard.writeText(message.content).catch(() => {
        console.log('Failed to copy to clipboard')
      })
    }
  }, [currentSession.messages])

  const handleSaveEntries = useCallback((messageId: string, entryIds: string[]) => {
    console.log('Save entries from message:', messageId, 'entries:', entryIds)
  }, [])

  const handleViewEntry = useCallback((entryId: string) => {
    console.log('View entry:', entryId)
  }, [])

  const handleSourcesChange = useCallback((sources: QuerySources) => {
    setCurrentSession((prev) => ({ ...prev, sources }))
  }, [])

  const handleSaveSession = useCallback(() => {
    setCurrentSession((prev) => {
      if (prev.isSaved) return prev

      const firstUserMsg = prev.messages.find((m) => m.role === 'user')
      const newSaved: SavedSession = {
        id: prev.id,
        title: firstUserMsg
          ? firstUserMsg.content.slice(0, 50) + (firstUserMsg.content.length > 50 ? '...' : '')
          : 'New Chat',
        createdAt: prev.messages[0]?.timestamp ?? new Date().toISOString(),
        lastMessageAt: prev.messages[prev.messages.length - 1]?.timestamp ?? new Date().toISOString(),
        messageCount: prev.messages.length,
        preview: firstUserMsg?.content ?? '',
      }

      setSavedSessions((sessions) => [newSaved, ...sessions])
      return { ...prev, isSaved: true }
    })
  }, [])

  const handleLoadSession = useCallback(
    (sessionId: string) => {
      const session = savedSessions.find((s) => s.id === sessionId)
      if (!session) return

      // In production this would load messages from a backend.
      // For the demo, switch to an empty session with the saved session's ID.
      setCurrentSession({
        id: session.id,
        isSaved: true,
        sources: { type: 'all' },
        messages: [],
      })
    },
    [savedSessions]
  )

  const handleDeleteSession = useCallback((sessionId: string) => {
    setSavedSessions((prev) => prev.filter((s) => s.id !== sessionId))
  }, [])

  const handleNewSession = useCallback(() => {
    setCurrentSession({
      id: `session-${Date.now()}`,
      isSaved: false,
      sources: { type: 'all' },
      messages: [],
    })
  }, [])

  return (
    <DiscoveryChat
      savedSessions={savedSessions}
      currentSession={currentSession}
      availableSources={discoveryAvailableSources}
      onSendMessage={handleSendMessage}
      onRegenerate={handleRegenerate}
      onCopyResponse={handleCopyResponse}
      onSaveEntries={handleSaveEntries}
      onViewEntry={handleViewEntry}
      onSourcesChange={handleSourcesChange}
      onSaveSession={handleSaveSession}
      onLoadSession={handleLoadSession}
      onDeleteSession={handleDeleteSession}
      onNewSession={handleNewSession}
    />
  )
}
